### PR TITLE
Refactor image preprocessing

### PR DESCRIPTION
**Pull request by wagoodman**
This was done for two reasons:
- preprocessing can only handle docker images. It would be ideal to one day expand this to other image formats
- this was already explicitly labeled as tech debt

### CODE REVIEW

**Comment by ccinelli** [comment]
It looks like this just re-shuffle code in different files. Am I wrong?

**Comment by wagoodman** [comment]
Mostly, yes. This abstracts the steps for any format that could be added later (such as OCI). I still need to refactor the `Parse()`, `Analyze()`, and `read()` sections a bit more. Another benefit is that this abstraction does not bail via an explicit exit, but instead by returning an error, which makes this much more testible (still need to add tests).

**Comment by willmurphyscode** [comment]
This code looks good, but I wish I knew more about how other image formats work. I'm worried that if we extract interfaces before we implement a second image analyzer, we'll make extra work for ourselves.

Would it be worth spiking an analyzer for runC images before we do this, and then seeing if all the interfaces we have still hold up? 

Or maybe the formats are all similar enough that my worry is unfounded. @wagoodman do you feel confident enough in how the analysis of other images will be similar or different from Docker images to go ahead with this?

**Comment by wagoodman** [comment]
Your worry is a fair one, I'm not entirely certain this is the right interface (for instance, will we only need a string to fetch and parse an image? or something more complex to indicate what to fetch?). However, I do feel like it's in the right direction and it is as simple as it can be for now. Also, since we're not at 1.0.0 yet there isn't any obligation to ensure interfaces won't change or break against previous versions.

**Pull request merged**
