### PR TITLE
Adding docker-archive source option

### PR DESCRIPTION
**Pull request by wagoodman**
Note: this should be merged after #234 .

This adds the ability to process a tar formatted archive as a result from the `docker image save ...` command (and `podman image save ...` for the default docker-formatted archive type). This should address #194.

### CODE REVIEW

**Comment by flickerfly** [comment]
Where do I get the docker image with this in it? I have a >20Gig image I need to investigate and evaluating directly from the tarbal sounds helpful.

**Comment by wagoodman** [comment]
@flickerfly evaluating directly from the tar will speed things up regarding the initial load, yes. The next release will have this option, I think in ~a week or so I'll have it out.

**Comment by flickerfly** [comment]
@wagoodman Marvelous, thank you!

**Comment by wagoodman** [comment]
@flickerfly Looks like I lied a bit about finding time to release :) . But good news, v0.9.0 is released and has what you are looking for. You can provide either `dive --source docker-archive <your-image>` or `dive docker-archive://<your-image>` once you save it out to a tar with `docker image save ...`.

**Comment by flickerfly** [comment]
Thanks!

**Pull request merged**
