### PR TITLE
Add details pane

### PR DESCRIPTION
**Pull request by wagoodman**

### CODE REVIEW

**Comment by im-n1** [comment]
Detail pane is cool but how do I scroll it?

**Comment by wagoodman** [comment]
It doesn't, the data is exportable with the `--json` flag (which skips the UI). I haven't given much thought to how that pane should be selectable. I'm open to suggestions... feel free to open an issue about it.

**Comment by im-n1** [comment]
With a tab key. We already know the tab sycles between windows (panes). Let's just add another.

**Comment by wagoodman** [comment]
I've added a set of issues for UI enhancements, including detail pane scrolling and selection (specifically #181)

**Pull request merged**
