### PR TITLE
Add feature "export tree view"

### PR DESCRIPTION
**Pull request by markruler**
Related: #296 

I don't know how to deal with the color code ("[33m" and "[0m"). Does anybody have a good idea?

image

### CODE REVIEW

**Comment by theAkito** [comment]
As a workaround you could process the input for these codes, the same way they are natively processed. You just look for the delimiters `[` and `m` and filter out anything in between, including the delimiters themselves.

Once you have this working, we can already use this feature, while it can be improved later with a perhaps more performant alternative of filtering out these colour codes.

**Review by wagoodman — CHANGES_REQUESTED** [review]
I can see a use case or two where I would want to get a filetree view out of dive in the form of a flat file, however, I think this needs more thought before committing to adding the feature:

- writing out the filetrees to `{home}/tree-{time}` seems somewhat surprising from the users perspective. Probably writing to the `pwd` would be less surprising. Maybe it would be even more ideal to copy the tree directly to the clipboard (though, I think making that cross platform would be challenging). I don't think I have a good alternative here, but I think this is the largest problem to solve.
- We should be trying to strip ANSI control sequences agnostically, something like https://github.com/acarl005/stripansi .
- The status bar (where the keybinding hint for "Export tree view" is shown) is getting cramped for space, maybe shortening to "Export tree" --a small detail, but would help.
- Should we also be outputting what the tree is describing? Maybe a small block that has the image name/digest, which layer this represents, whether this is just the layer contents or an aggregation of multiple layers, etc. Otherwise exporting multiple trees would be confusing... the user would have to remember what actions they took chronologically.

I appreciate the effort so far and apologies it's taken a while to respond!

**Comment by markruler** [comment]
> I can see a use case or two where I would want to get a filetree view out of dive in the form of a flat file, however, I think this needs more thought before committing to adding the feature:
> 
> * writing out the filetrees to `{home}/tree-{time}` seems somewhat surprising from the users perspective. Probably writing to the `pwd` would be less surprising. Maybe it would be even more ideal to copy the tree directly to the clipboard (though, I think making that cross platform would be challenging). I don't think I have a good alternative here, but I think this is the largest problem to solve.
> * We should be trying to strip ANSI control sequences agnostically, something like https://github.com/acarl005/stripansi .
> * The status bar (where the keybinding hint for "Export tree view" is shown) is getting cramped for space, maybe shortening to "Export tree" --a small detail, but would help.
> * Should we also be outputting what the tree is describing? Maybe a small block that has the image name/digest, which layer this represents, whether this is just the layer contents or an aggregation of multiple layers, etc. Otherwise exporting multiple trees would be confusing... the user would have to remember what actions they took chronologically.
> 
> I appreciate the effort so far and apologies it's taken a while to respond!

Thank you for your review. I agree with your great idea and will approach it in an easy way first.

I'll commit one by one.
- [ ] change the output directory: from `$HOME` to `$PWD`
- [ ] strip ANSI: `[33m`, `[0m`, ...
- [ ] shorten the keybinding hint: `Export tree view` -> `Export tree`
- [ ] make a small block describing tree info include image name/digest

**Comment by markruler** [comment]
image

image

**Pull request closed without merging**
