### PR TITLE
use separate goreleaser config file to generate docker images based on alpine

### LINKED ISSUE #243: Use alpine as the base image (again)
A month ago (https://github.com/wagoodman/dive/commit/c83bc9e3d03356a942a90b9a6c9832e336363229#diff-3a895417c300af3c34fab6ebb556e984), `CGO_ENABLED=0` was removed from `.goreleaser.yml` because some dependencies of podman do require dynamic loading. I.e., it is no longer possible to build `dive` statically. As a result, binary files built on Ubuntu of Fedora host won't work in Alpine containers. So, Alpine based images were dropped in favour of `debian:sid-slim` (https://github.com/wagoodman/dive/commit/65f87b00a947a20dc62f57cfef1c59009ba2fec2#r35804708). However, these images are 10-15 times larger than previous `slim` variants.

A possible workaround (suggested in https://github.com/wagoodman/dive/commit/65f87b00a947a20dc62f57cfef1c59009ba2fec2#r35815381) is to convert podman support into a plugin, so that static compilation is possible for users that do not need it. However, this would be cumbersome for maintenance.

Instead, I suggest executing `goreleaser` twice. Once on an Ubuntu or Fedora host in order to generate `deb` and `rpm` artifacts. Then, inside a `golang:alpine` container, in order to generate docker images. Feature-wise, all artifacts would be equivalent; the only difference being that some depend on `glib` and others on `musl`.

Build dependencies in a `golang:alpine` container are `gpgme-dev gcc musl-dev btrfs-progs-dev lvm2-dev` and runtime dependencies are `gpgme device-mapper`. For example:

```Dockerfile
ARG ALPINE_VERSION="3.10"
ARG DOCKER_CLI_VERSION="19.03.1"

FROM alpine:$ALPINE_VERSION AS docker
ARG DOCKER_CLI_VERSION
RUN apk -U --no-cache add curl \
 && curl -L https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_CLI_VERSION.tgz | tar -xzf - docker/docker --strip-component=1 -C /tmp

FROM alpine:$ALPINE_VERSION
COPY --from=docker /tmp/docker /usr/local/bin
COPY dive /dive
RUN apk add -U --no-cache gpgme device-mapper
ENTRYPOINT ["/dive"]
```

```sh
#!/usr/bin/env sh

set -e

cd "$(dirname $0)"

docker build -t wagoodman/dive:golang- <<EOF
FROM golang:alpine AS build
RUN apk add -U --no-cache gpgme-dev gcc musl-dev btrfs-progs-dev lvm2-dev
EOF

docker run --rm -v /$(pwd)://src -w //src wagoodman/dive:golang sh -c "go build -o slim/dive -ldflags '-s -w'"

docker build -t wagoodman/dive:slim .
```

### PR DESCRIPTION
**Pull request by 1138-4EB**
Close #243

In this PR, `.goreleaser.yml` is split (a new `.goreleaser.docker.yml` file is created) and `Dockerfile` is modified to use `alpine` as a base image (again).

Since `dive` is not statically compiled any more, it needs to be built inside an `alpine` docker container (or on an Alpine host). To do so, script `docker.sh` is added. Temporal image `wagoodman/dive:dev`is built, which contains build dependencies. Then, goreleaser is executed inside the dev container.

Note that images are not pushed yet. This is because I'd like to discuss whether to build `wagoodman/dive:dev` in `docker.sh` or to add a GHA workflow to build it periodically (say weekly). Also, I wonder if the `docker run` command in `docker.sh` should be merged into the makefile. I'll keep this PR as a draft for now.

### CODE REVIEW

**Comment by wagoodman** [comment]
This is fantastic, thanks for the support! 

Building `wagoodman/dive:dev` ephemerally in `docker.sh` will work just fine --that is, I'd be happy to merge it as is and work out enhancement details. If you were up for the extra mile, then the GHA workflow would be great (and the way to go). As for the `docker run`, this should stay in the `docker.sh` until I figure the best way to merge scripts/makefile and Circle/GHA (I'm up for it, I need to invest a bit more time in a more robust CI for dive).

**Comment by 1138-4EB** [comment]
> Building `wagoodman/dive:dev` ephemerally in `docker.sh` will work just fine --that is, I'd be happy to merge it as is and work out enhancement details. If you were up for the extra mile, then the GHA workflow would be great (and the way to go).

It is actually no effort for me. But I need you to setup a couple of secrets for me. Please add `DOCKER_USER` and `DOCKER_PASS` to https://github.com/wagoodman/dive/settings/secrets. That will allow to push `wagoodman/dive:dev` (and other images) to hub.docker.com. If credentials for quay.io are different, those will be required later.

Alternatively, we can use GitHub's Registry (`docker.pkg.github.com/wagoodman/dive/dive:dev`. The advantage is that the `GITHUB_TOKEN` that is available in GitHub Actions by default is enough to push/pull from it. The disadvantage is that GitHub's Registry does not support unauthorized access (not even for reading). Hence, it is cumbersome to use images locally.

> As for the `docker run`, this should stay in the `docker.sh` until I figure the best way to merge scripts/makefile and Circle/GHA (I'm up for it, I need to invest a bit more time in a more robust CI for dive).

Ok.

**Comment by wagoodman** [comment]
GitHub Registry seems to be the right choice for security: keeping the dev image inaccessible from the "prod" docker hub registry. The extra login step is annoying, though not really a problem.

**Comment by 1138-4EB** [comment]
> GitHub Registry seems to be the right choice for security: keeping the dev image inaccessible from the "prod" docker hub registry. The extra login step is annoying, though not really a problem.

Then, I need you to sign for the beta of the GitHub Registry (https://github.com/features/package-registry). Once it is enabled, the default GITHUB_TOKEN will have access to your own registry.

Apart from that, this PR is ready to merge. However, note that merging this now will break the automatic publication of docker images. In order to enable it, `--snapshot --skip-publish` options must be removed from `docker.sh` and docker/quay secrets must be added and passed to the `wagoodman/dive:dev` container.

Alternatively, it is possible to `docker push quay.io/wagoodman/dive` and `docker push wagoodman/dive` outside of the container. Say, as an additional step after `docker images`.

How do you release images now? Do you execute goreleaser on your workstation/laptop?

**Comment by 1138-4EB** [comment]
> We strongly recommend that you do not use this feature for high-value workflows and content during the beta period

I forgot to comment this. I believe that this note is because many things have been changing during the last months, and because the service has been 'free' during this period. Nevertheless, it will be out of beta next week; hence, each user will be able to define the complexity of the workflow within the limit of their budget. For public open source projects, the budget is 'maximum 20 parallel jobs'. No minutes per month limit.

**Comment by wagoodman** [comment]
Today, I build and release images from my laptop. However, this weekend I'll start working on incorporating a pipeline that cuts releases on tag. Additionally I'll be adding steps that will test package installations for various platforms/OSs.

This PR is a great starting point --I'll merge it and open another PR to accommodate the 0.9.1 changes I put in this morning.

**Pull request merged**
