### PR TITLE
Add layer-wise filesystem information to the analysis json file

### PR DESCRIPTION
**Pull request by Akash-Nayak**
Add layer-wise filesystem information to the analysis which is written to a json file while running dive with `-j` or `--json` flag.

### CODE REVIEW

**Comment by amuttsch** [comment]
I'd love to see this feature in dive too. Are there any plans on merging this @wagoodman ? Thanks!

**Comment by wagoodman** [comment]
Sorry! I didn't mean to close this, I renamed the master branch to main... I should have switched the target here first.

**Comment by Akash-Nayak** [comment]
NP. I have re-opened the PR against the `main` branch.

**Comment by wagoodman** [comment]
Thanks @Akash-Nayak , sorry for the extra work

**Comment by Akash-Nayak** [comment]
No problem. Please review the new PR when you are free. :)

**Pull request closed without merging**
