### PR TITLE
Move formula to homebrew-core

### PR DESCRIPTION
**Pull request by chenrui333**
I think it would be nice to add this formula into homebrew-core. So I went ahead creating a PR for it, https://github.com/Homebrew/homebrew-core/pull/42492.

### CODE REVIEW

**Comment by wagoodman** [comment]
Thanks @chenrui333 . I don't have a mac handy, but it seems that I can help out on a linux box just fine too. Let me know if you'd like help troubleshooting the issue your seeing here https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/45745/console . (just for tracking, this addresses #97 )

**Comment by chenrui333** [comment]
Yeah, my machine is Mac, I have tested locally before the submission, not quite sure why it fails in the CI. I will double check now.

**Comment by chenrui333** [comment]
@wagoodman, Given the homebrew-core PR build issue reolsved, I went ahead of creating a migration PR for `homebrew-dive` as well (which would depend on the homebrew-core PR).

**Comment by chenrui333** [comment]
@wagoodman the PR https://github.com/Homebrew/homebrew-core/pull/42492 has been merged, I think we can merge this one now :)

**Comment by md5** [comment]
@chenrui333 Any chance the `docker` dependency can be removed? I have Docker for Mac install and do not want to install `docker` from Homebrew...

**Comment by chenrui333** [comment]
Sure, I can remove that, I was thinking more from runtime dependency perspective. I will do it now.

**Comment by chenrui333** [comment]
@md5 I have removed the docker dependency in the homebrew-core and PR got merged. :)

**Comment by md5** [comment]
Thanks!

**Comment by wagoodman** [comment]
@chenrui333 thanks for the homebrew update! Indeed the docker dependency is optional. As long as you can connect to a docker socket somewhere, you don't necessarily need the docker client.

**Comment by wagoodman** [comment]
Sorry for the delay, thanks for your time @chenrui333

**Comment by chenrui333** [comment]
No worries, thanks for the merge!  🎉

**Pull request merged**
