### PR TITLE
Changes keys bindings

### PR DESCRIPTION
**Pull request by slash-cyberpunk**
Mac OS have system bind Ctrl+Space and Ctrl+Slash

### CODE REVIEW

**Comment by kamly** [comment]
mac os keybindings, use Ctrl+Space change the Input type

image

**Comment by slash-cyberpunk** [comment]
Yes, this change input type or run spotlight

**Comment by wagoodman** [comment]
Awesome, this makes sense. Can you make two more adjustments?

1. Allow both the original key bindings and the new keybindings for now since there are already users used to the existing bindings.
2. Update the key hints to show the new keybindings: https://github.com/wagoodman/dive/blob/master/ui/statusview.go#L79-L80

**Comment by slash-cyberpunk** [comment]
1. I don't know how to do? Do you have warrants how to do this?
2. No problem.

**Comment by wagoodman** [comment]
Yeah, instead of modifying the existing keybinding lines you can duplicate them (lines 149-154) and make your modifications to the duplicated statements.

**Comment by slash-cyberpunk** [comment]
Done

**Comment by TJM** [comment]
That's interesting... on my mac, the system key binding for Spotlight is CMD+SPACE. I am not sure about changing input type, that must be an i18n issue :)

**Comment by slash-cyberpunk** [comment]
@TJM https://support.apple.com/en-us/HT201236

> Command–Space bar: Show or hide the Spotlight search field. To perform a Spotlight search from a Finder window, press Command–Option–Space bar. (If you use multiple input sources to type in different languages, these shortcuts change input sources instead of showing Spotlight. Learn how to change a conflicting keyboard shortcut.)

**Comment by TJM** [comment]
@slash-cyberpunk Yes, that seems to match what I am seeing, without multiple inputs configured, I get the search window. Since you can't possibly account for all possible system shortcut keys that someone might setup, maybe it would be best to have a "config" file? (~/.diverc ?)

Although, I do feel like "<tab>" is a better key for switching views. :)

**Comment by wagoodman** [comment]
Thanks @slash-cyberpunk for the contribution, I think I'll be revisiting keybindings in the near future.

**Pull request merged**
