### PR TITLE
Add package installation testing

### PR DESCRIPTION
**Pull request by wagoodman**
This adds the ability to test the deb/rpm packages as well as do a smoke-ish like test for running on mac, windows, and linux. Any comments on approach/improvements are welcome!

### CODE REVIEW

**Comment by 1138-4EB** [comment]
I am not sure about *"This will run on merge to master, and for PRs with folks that also are part of the GHA beta"*. On the one hand, the condition is changed in this PR to `on: [ push ]`. On the other hand, even if contributors are not part of the GHA beta, when a PR is opened, tests should be executed. Moreover, if the contributor is part of the beta, tests will be executed twice: one as a push on the fork, and another time as a PR here.

**Comment by kickinranch** [comment]
@1138-4EB quite right, when I tried this out it was in a private repo, which I believe why it was not running --comment removed.

**Comment by wagoodman** [comment]
@1138-4EB quite right, when I tried this out it was in a private repo, which I believe why it was not running --comment removed.

**Comment by 1138-4EB** [comment]
@wagoodman, IMHO you should keep `pull_request` and use `if` fields to avoid specific steps being executed, should you want to. Otherwise, you will need to blindly review PRs, or go to the forks to see the tests.

**Comment by wagoodman** [comment]
Ah I hadn't realized this is what you were pointing out. I'll go back and add this in, thanks!

**Pull request merged**
