### PR TITLE
Tidy up go dependencies

### PR DESCRIPTION
**Pull request by tklauser**
Run `go mod tidy` to tidy up unused hashes in `go.sum` and remove the
unused `golang.org/x/crypto` dependency from `go.mod`.

### CODE REVIEW

**Comment by tklauser** [comment]
Thanks for this awesome tool @wagoodman!

**Comment by tklauser** [comment]
Static analysis CI job failed due to `staticcheck` error. I send PR #291 with a fix.

**Comment by tklauser** [comment]
Rebased on `master` with #291 merged.

**Comment by wagoodman** [comment]
Thanks for the contribution! (and patience :) )

**Pull request merged**
